# Generated by Django 4.0.5 on 2023-08-29 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='XXX', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(default='No Description is Set')),
                ('doc_path', models.CharField(default='Documents', max_length=200)),
                ('num_projects', models.IntegerField(default=14)),
                ('num_lessons', models.IntegerField(default=42)),
                ('github_repo', models.CharField(default='~/Github/UNC-BACS200-2022-Spring', max_length=200)),
                ('week', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True, null=True)),
                ('server', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('course', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(default='No title', max_length=200)),
                ('doctype', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200, null=True)),
                ('course', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('folder', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.content')),
            ],
        ),
    ]
