# Generated by Django 4.0.5 on 2023-09-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('server', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
