# Generated by Django 4.2.5 on 2026-02-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("brainchild", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("pub_path", models.CharField(max_length=300)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="brainchild.pubcategory",
                    ),
                ),
            ],
        ),
    ]
