# Generated by Django 4.2.5 on 2026-02-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brainchild", "0002_pub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pub",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pub",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pubcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
