# Generated by Django 4.2.5 on 2026-02-04 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brainchild", "0005_blogpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="content",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="title",
        ),
    ]
