# Generated by Django 4.2.5 on 2026-02-04 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brainchild", "0006_remove_blogpage_content_remove_blogpage_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pub",
            old_name="title",
            new_name="name",
        ),
    ]
