# Generated by Django 4.2.5 on 2026-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brainchild", "0007_rename_title_pub_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubcategory",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
