# Generated by Django 4.2.5 on 2026-02-05 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brainchild", "0008_pubcategory_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pub",
            old_name="subtitle",
            new_name="title",
        ),
    ]
