# Generated by Django 4.0.5 on 2023-08-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, default='Mark Seaman', max_length=100)),
                ('description', models.TextField(blank=True, default='None', null=True)),
                ('doc_path', models.CharField(default='Documents', max_length=200)),
                ('image_path', models.CharField(max_length=200, null=True)),
                ('css', models.CharField(max_length=200, null=True)),
                ('domain', models.URLField(null=True)),
                ('url', models.URLField()),
                ('logo', models.CharField(max_length=200, null=True)),
                ('words', models.IntegerField(default=0)),
                ('cover_image', models.CharField(blank=True, max_length=200, null=True)),
                ('menu', models.TextField(blank=True, null=True)),
                ('pub_type', models.CharField(default='blog', max_length=20)),
                ('auto_remove', models.BooleanField(default=False)),
                ('auto_contents', models.BooleanField(default=False)),
                ('auto_index', models.BooleanField(default=False)),
                ('index_folders', models.BooleanField(default=False)),
                ('index_months', models.BooleanField(default=False)),
                ('simple_index', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(default='No title', max_length=200)),
                ('doctype', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200, null=True)),
                ('folder', models.IntegerField(default=0)),
                ('words', models.IntegerField(default=0)),
                ('retain_object', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='publish.pub')),
            ],
        ),
    ]
