# Generated by Django 4.2.5 on 2023-11-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publish", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, default="Mark Seaman", max_length=100),
                ),
                ("title", models.CharField(default="No title", max_length=200)),
                ("text", models.TextField(blank=True, default="None", null=True)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
    ]
