# Generated by Django 4.2.5 on 2023-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
