# Generated by Django 4.2.5 on 2023-10-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writer", "0002_alter_author_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="profile_picture",
        ),
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
