#!/bin/bash
# Linux Shell Contexts

# Path Context
syspath="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
brew=/opt/homebrew/bin:/opt/homebrew/sbin
sublime="/Applications/Sublime Text.app/Contents/SharedSupport/bin"
vscode1="/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="$brew:$sublime:$vscode1:$syspath"
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="/usr/local/texlive/2025basic/bin/universal-darwin:$PATH"

# Python
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"


# ------------
# Variables

export a="$HOME/Archive"
export b="$o/forge/books"
export d="$p/Documents"
export EDITOR="$sublime/subl -w"
export f="$o/forge"
export g="$HOME/Github"
export h="$HOME/Hammer"
export i="/Users/seaman/Library/Mobile Documents/com~apple~CloudDocs/Desktop"
export l="$d/Shrinking-World-Pubs/log"
export m="$a/rcp/mbw"
export mcp="$h/Obsidian/forge/mcp"
export n="$a/ntsh"
export o="$h/Obsidian"
export p="$o/Private"
export s="$d/Shrinking-World-Pubs"
export t="$o/Private/history/2026"

# ------------
# ALIASES

# Unused
alias j='echo unused'
alias n='echo unused'
alias v='echo unused'
alias y='echo unused'
alias z='echo unused'

# Pub Script
alias forge="d $o/forge"
alias ev='open -a Evernote'
alias build='agent build'
alias mkpub='order mkpub'
alias cover='order cover'
alias content='order content'
alias json='order json'
alias order="cd $h; python Obsidian/forge/mcp/mcp_order.py"
alias manuscript='order manuscript'
alias words='order words'

# Project Scripts
alias activity='week activity'
alias day='task 1'
alias doit=./Obsidian/forge/mcp/doit.py
alias e='subl'
alias ea='subl ~/Hammer/config/zshrc'
alias hammer="cd $h && source ~/.zshrc"
alias month='task 30'
alias pub='d $d/Shrinking-World-Pubs'
alias quote=./Obsidian/forge/mcp/quote.py
alias rcpe='e "/Users/seaman/Library/Mobile Documents/com~apple~CloudDocs/Desktop/.ntsh/rcpf"'
alias rcp="/Users/seaman/Library/Mobile\ Documents/com~apple~CloudDocs/Desktop/.ntsh/rcp"
alias task='pm task'
alias today='task 1 today'
alias week='task 7'
alias year='task 365'

# MCP
alias books="ls -lt $b"
alias agent="python $mcp/tool.py"
alias cpr='cd $p && c'
alias pub='agent publication'
alias o="d $o; open -a Obsidian $o"
alias ob="d $o"
alias social='agent social'
alias private="d $p; open -a Obsidian $p"
alias cprc='cp ~/Hammer/config/zshrc ~/.zshrc && . ~/.zshrc'
alias todo='pm todo'
alias dropbox='open ~/Dropbox/Stacie-Mark'
alias treed='tree -d -L 3'
alias promo='agent promo'
alias m='e Documents/mastodon'
alias i='d $i; open $i'
alias a='open https://chat.openai.com/'

# Websites
alias hoopla='open https://www.hoopladigital.com/my/hoopla'
alias gmail='open https://mail.google.com'
alias chat='open  https://mail.google.com/chat'
alias bard='open  https://bard.google.com'
alias github='open https://github.com/Mark-Seaman?page=1&tab=repositories'
alias tella='open https://auth.tella.tv/u/login/identifier?state=hKFo2SBtbUdFWEpmNl9qOWRRWFFSV3dYVk9DSVZCN3BGT1poTKFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIGNOOGs2R2JFQ0RyWE1nVzBGY0tlS09MOEdEOHFxcDlNo2NpZNkgeTdQM0tPOGQ5QzhsWGw0NmVLalFLVFh6VUY3UnhxbWs'
alias uncmail='open https://outlook.office.com'
alias maps='open https://www.google.com/maps/place/404+Crystal+Beach+Dr,+Windsor,+CO+80550/@40.461123,-104.902838,17z/data=!3m1!4b1!4m2!3m1!1s0x876eae2fe3eaa51b:0xdf4f905a65d54401'

# Linux command context
alias g='grep --color=auto'
alias l='ls -al'
alias lc='wc -l'
alias u='d ..'
alias host="python -c 'import platform;print(platform.node())'"
alias h='history 100'
alias p=python
alias w='open https://mail.google.com/mail/u/0/#inbox'

# Git aliases
alias ga='git add -A . && git commit -m'
alias gc='pm vc commit'
alias gco='git checkout'
alias gd='git diff'
alias gh='d $g'
alias gl='git log --name-only'
alias gs='pm vc status'
alias pull='pm vc pull'
alias push='pm vc push'
alias s='git status'
alias vc='cd $p && pm vc'

# Django aliases
alias pm='python manage.py'
alias r='sh $h/config/runserver'
alias k='pkill -f "python manage.py runserver"'
alias migrate='pm makemigrations && pm migrate'
alias x='pm x'
alias deploy='x deploy'

# Servers
alias imac='ssh seaman@marks-imac.local'
alias macbook='ssh markseaman@marks-macbook.local'
alias ntsh='. $n/zshrc'
alias unpack='pm pack open'
alias pack='pm pack close'
alias imager='pm imager'

# Test aliases
alias t='reset && pm tst run'
alias tst='pm tst run'
alias tlike='pm tst like && tst'
alias tres='pm tst results | less'
alias treset='pm tst reset'
alias dt='pm test'
alias q='pm tst quick'
alias qt='pm tst quick'


# -----------------
# Linux functions

function d {
    directory=$1
    [ -z "$1" ] && directory="$h"
    [ -z "$1" ] || echo $directory && cd $directory && l
}

# Big commit on current directory
function c {
    git add -A .       &&
    git commit -m "$*" &&
    git push
    git status
}

# Copy a file tree
function cptree {
    rsync -auv "$1/" "$2"
}

# Create a post on mastodon
function post {
    msg=`cat Documents/mastodon/$1`
    echo toot post \"$msg\"
}

# List the path in readable form
function path {
    echo $PATH | perl -pe s/:/\\n/g
}

# Show the Python setup
function py {
    echo "Python environment"
    echo PYTHON_PATH = `which python`
    echo PYENV = `pyenv which python`
    echo "Python Packages"
    pip freeze
}

# Start directory
export PS1="%3~ : "
cd ~/Hammer
ls
figlet `host`

