# Generated by Django 4.0.5 on 2023-01-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasktype_activity_task_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity',
            new_name='type',
        ),
    ]
